# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Listerr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Listerr
  pod 'Firebase/Core', '~> 5.20.2'
  pod 'GoogleSignIn', '~> 4.4.0'
  # target 'Listerr-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'ListerrTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# target 'Listerr-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Listerr-tvOS

  # target 'Listerr-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

# end
